<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <title>Abstracts Report - {{ config('conference.short_name') }} {{ config('conference.year') }}</title>
    <style>
        @page {
            margin: 1cm;
        }
        body {
            font-family: 'Helvetica', 'Arial', sans-serif;
            font-size: 9pt;
            color: #1e293b;
            line-height: 1.5;
        }
        .header {
            margin-bottom: 30px;
            border-bottom: 2px solid #3b82f6;
            padding-bottom: 20px;
        }
        .header-table {
            width: 100%;
            border: none;
        }
        .header-table td {
            border: none;
            padding: 0;
            vertical-align: bottom;
        }
        .logo-text {
            font-size: 24pt;
            font-weight: bold;
            color: #1e293b;
            margin: 0;
        }
        .logo-accent {
            color: #3b82f6;
        }
        .report-title {
            font-size: 14pt;
            color: #64748b;
            margin-top: 5px;
        }
        .meta-info {
            text-align: right;
            font-size: 8pt;
            color: #64748b;
        }
        table {
            width: 100%;
            border-collapse: collapse;
            margin-bottom: 20px;
        }
        th {
            background-color: #f8fafc;
            color: #475569;
            font-weight: bold;
            text-transform: uppercase;
            font-size: 8pt;
            letter-spacing: 0.05em;
            padding: 12px 8px;
            border-bottom: 2px solid #e2e8f0;
            text-align: left;
        }
        td {
            padding: 10px 8px;
            border-bottom: 1px solid #f1f5f9;
            vertical-align: top;
        }
        .status-badge {
            display: inline-block;
            padding: 2px 6px;
            border-radius: 4px;
            background-color: #f1f5f9;
            font-size: 7pt;
            font-weight: bold;
        }
        .footer {
            position: fixed;
            bottom: 0;
            width: 100%;
            font-size: 7pt;
            color: #94a3b8;
            text-align: center;
            border-top: 1px solid #f1f5f9;
            padding-top: 10px;
        }
        .description-cell {
            font-size: 8pt;
            color: #475569;
            line-height: 1.4;
        }
        tr:nth-child(even) {
            background-color: #fafafa;
        }
    </style>
</head>
<body>
    <div class="header">
        <table class="header-table">
            <tr>
                <td>
                    <h1 class="logo-text">{{ config('conference.short_name') }} <span class="logo-accent">2026</span></h1>
                    <div class="report-title">Scientific Abstract Intelligence Report</div>
                </td>
                <td class="meta-info">
                    <strong>Generated By:</strong> {{ $user->name }}<br>
                    <strong>Date:</strong> {{ $generated_at->format('M d, Y | H:i') }}<br>
                    <strong>Total Records:</strong> {{ $abstracts->count() }}
                </td>
            </tr>
        </table>
    </div>

    <table>
        <thead>
            <tr>
                @foreach($columns as $col)
                    <th>
                        @php
                            $labels = [
                                'id' => 'ID',
                                'title' => 'Title',
                                'conference_code' => 'Code',
                                'subtheme' => 'Subtheme',
                                'author_title' => 'Salutation',
                                'author_name' => 'Author',
                                'author_email' => 'Email',
                                'author_institute' => 'Institution',
                                'author_country' => 'Country',
                                'status' => 'Status',
                                'created_at' => 'Submitted',
                                'updated_at' => 'Updated',
                                'reviewer_names' => 'Reviewers',
                                'average_score' => 'Score',
                                'recommendations' => 'Rec.',
                                'description' => 'Abstract Summary'
                            ];
                            echo $labels[$col] ?? ucfirst(str_replace('_', ' ', $col));
                        @endphp
                    </th>
                @endforeach
            </tr>
        </thead>
        <tbody>
            @foreach($abstracts as $abstract)
                <tr>
                    @foreach($columns as $col)
                        <td class="{{ $col === 'description' ? 'description-cell' : '' }}">
                            @if($col === 'id')
                                <strong>#{{ $abstract->id }}</strong>
                            @elseif($col === 'title')
                                {{ $abstract->title }}
                            @elseif($col === 'conference_code')
                                <code style="background: #f1f5f9; padding: 2px 4px; border-radius: 3px;">{{ $abstract->conference_code ?? '-' }}</code>
                            @elseif($col === 'subtheme')
                                {{ $abstract->subtheme }}
                            @elseif($col === 'author_title')
                                {{ $abstract->user->title ?? '' }}
                            @elseif($col === 'author_name')
                                @if($abstract->user)
                                    {{ $abstract->user->first_name }} {{ $abstract->user->last_name }}
                                @else
                                    {{ $abstract->author_name }}
                                @endif
                            @elseif($col === 'author_institute')
                                {{ $abstract->author_institute }}
                            @elseif($col === 'author_email')
                                <span style="color: #3b82f6;">{{ $abstract->user->email ?? '-' }}</span>
                            @elseif($col === 'status')
                                <div class="status-badge">{{ ucfirst(str_replace('_', ' ', $abstract->status)) }}</div>
                            @elseif($col === 'created_at')
                                {{ $abstract->created_at->format('Y-m-d') }}
                            @elseif($col === 'updated_at')
                                {{ $abstract->updated_at->format('Y-m-d') }}
                            @elseif($col === 'average_score')
                                @php
                                    $scores = $abstract->reviews->where('status', 'submitted')->pluck('score');
                                    $avg = $scores->count() > 0 ? round($scores->avg(), 1) : '-';
                                @endphp
                                <strong style="color: {{ $avg >= 4 ? '#059669' : ($avg >= 3 ? '#d97706' : '#1e293b') }}">{{ $avg }}</strong>
                            @elseif($col === 'reviewer_names')
                                <div style="font-size: 7pt;">
                                    {{ $abstract->reviewer1->name ?? '' }}<br>
                                    {{ $abstract->reviewer2->name ?? '' }}
                                </div>
                            @elseif($col === 'recommendations')
                                <em style="font-size: 7pt;">{{ $abstract->reviews->where('status', 'submitted')->pluck('recommendation')->map(fn($r) => ucfirst(str_replace('_', ' ', $r)))->join(', ') }}</em>
                            @elseif($col === 'description')
                                {{ Str::limit(strip_tags($abstract->description), 200) }}
                            @else
                                -
                            @endif
                        </td>
                    @endforeach
                </tr>
            @endforeach
        </tbody>
    </table>

    <div class="footer">
        {{ config('conference.edition') }} {{ config('conference.name') }} {{ config('conference.year') }} - Official Abstract Report | Generated via Admin Portal | Page [page_num] of [total_pages]
    </div>
</body>
</html>
